import json
from inputForScrapper import get_data_for_scrapper
from generateDescription import read_url_from_file, web_scraper, get_description, generate_description, divide_text
from insertData import update_description_industry_inFirebase

get_data_for_scrapper()

# Read the URL from the companyURL.txt file
url = read_url_from_file()

# Perform web scraping, which returns "about us" URL.
result = web_scraper(url, keywords=["About", "Company", "Blog", "Despre"], protocols=["http", "https"])

# If a link for "about us" is found:
if result:
    # Text is all text from "about us" page
    text = get_description(result)

    # Generate description based on the extracted text
    descriptionANDidnustry = generate_description(text)

    #Extraxt Industry and Description from text generated by gpt
    industry, description = divide_text(descriptionANDidnustry)

    # Save the generated description and industry into  description.txt file in dictionary form
    output_data = {
        "companyDescription": description,
        "selectedIndustry": industry
    }

    with open("description.txt", "w") as output_file:
        json.dump(output_data, output_file, indent=2)

update_description_industry_inFirebase()